### ISSUE TITLE
Problem with panel images

### ISSUE THREAD

**Issue by mauphie** [acb-studio/kirby-cloudinary-sync#2]
Great plugin and very easy to use! So far everything works great except for one thing:

In the panel, the images show up on the parent page. But when I create a section elsewhere in the panel, the images don't appear. In my screenshot below, all the blank images have had the images pushed to Cloudinary, the one with an image hasn't been pushed yet.

<img width="958" alt="Screenshot 2025-01-15 at 1 23 03 PM" src="https://github.com/user-attachments/assets/1fb43f39-55b3-4d1d-963d-6f8f69277f24" />

**Comment by agathesf** [comment]
Same issue here! I'm just commenting to keep track of the situation :)

**Comment by jonathan-reisdorf** [comment]
Thank you for reporting, I'll finally have a look at this this week!

**Comment by jonathan-reisdorf** [comment]
Unfortunately, I cannot reproduce the issue locally, both files section and files field work for me for pushed and unpushed images (even in conjunction with the `removeAssetsLocally` flag). To help circle the problem, could you please post which version of Kirby you are using the plugin with, and perhaps post the blueprint, a redacted version of your cloudinary plugin config or other additional information which may help reproduce the issue. Also, I have tried things out with a new installation without pre-existing images, so it would be good to know "in which order you've done what", and also, if you are using a custom file blueprint/template. Also it may help to isolate the issue if you could open your DevTools, go into the inspector and have a look at the URL that is (or isn't) generated for the broken images. Thank you!

**Comment by agathesf** [comment]
I'm currently using **`Kirby 4.4.0`** and used `'removeAssetsLocally' => false` in my config file.

Here is my blueprint `work.yml` : 
```
        fields:
            coverImage:
              width: 1/2
              type: files
              multiple: false
              layout: cards
              size: huge
              query: page.images
              label: Choisir une image de couverture
              required: true
              image:
                cover: true
```

There is no issue on the images preview on a `type: layout` :

```
            gallery:
                label: Galerie
                type: layout
                layouts:
                  - "1/1"
                  - "1/2, 1/2"
                  - "1/3, 2/3"
                  - "2/3, 1/3"
                fieldsets:
                  - image 
```
 
Also, I have the same issue whether I push existing files or upload new ones. 

Feel free to ask for more informations if I've missed any ! :)
